### ISSUE TITLE
Add feature to be able to use `rustls-tls` instead of `native-tls`.

### ISSUE THREAD

**Issue by xfbs** [naughie/reverse-proxy-service#1]
Hey, awesome work here!

I think it would be neat to be able to select `rustls-tls` instead of the default `native-tls` for people who don't want to pull in OpenSSL for some reason.

**Comment by naughie** [comment]
Thank you for nice suggestion!

I would like to add support for `hyper_rustls` in a week.
Maybe we will be able to switch `rustls`/`native-tls` by features, just like the `reqwest` crate.
